old_sound_rabbit_mq:
  connections:
    default:
      url: '%env(RABBITMQ_URL)%'
  producers:
    free_day:
      connection: default
      exchange_options: { name: 'free_day.exchange', type: 'direct' }
  consumers:
    free_day:
      connection: default
      exchange_options: { name: 'free_day.exchange', type: 'direct' }
      queue_options:
        name: 'set.free_day.queue'
      callback: App\Consumer\FreeDayConsumer